services:
  - type: web
    plan: free
    name: resume_advisor
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn resume_advisor.asgi:application -k uvicorn.workers.UvicornWorker"